
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Oct  4 2025 00:48:19 IST (Oct  3 2025 19:18:19 UTC)

// Verification Directory fv/ks_adder 

module ks_adder(clk, rst, a, b, cin, sum, cout);
  input clk, rst, cin;
  input [15:0] a, b;
  output [15:0] sum;
  output cout;
  wire clk, rst, cin;
  wire [15:0] a, b;
  wire [15:0] sum;
  wire cout;
  wire [15:0] b_temp;
  wire [15:0] a_temp;
  wire cin_temp, n_0, n_1, n_4, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_83, n_84;
  DFCNQD1 cout_reg(.CDN (n_47), .CP (clk), .D (n_46), .Q (cout));
  DFCNQD1 \sum_reg[15] (.CDN (n_47), .CP (clk), .D (n_45), .Q
       (sum[15]));
  AO22D0 g2599__2398(.A1 (n_44), .A2 (n_43), .B1 (b_temp[15]), .B2
       (a_temp[15]), .Z (n_46));
  XOR2D1 g2600__5107(.A1 (n_44), .A2 (n_43), .Z (n_45));
  DFCNQD1 \sum_reg[14] (.CDN (n_47), .CP (clk), .D (n_42), .Q
       (sum[14]));
  XOR2D1 g2603__6260(.A1 (n_41), .A2 (n_40), .Z (n_42));
  AO22D0 g2602__4319(.A1 (n_41), .A2 (n_40), .B1 (b_temp[14]), .B2
       (a_temp[14]), .Z (n_44));
  DFCNQD1 \sum_reg[13] (.CDN (n_47), .CP (clk), .D (n_39), .Q
       (sum[13]));
  XOR2D1 g2606__8428(.A1 (n_38), .A2 (n_37), .Z (n_39));
  AO22D0 g2605__5526(.A1 (n_38), .A2 (n_37), .B1 (b_temp[13]), .B2
       (a_temp[13]), .Z (n_41));
  DFCNQD1 \sum_reg[12] (.CDN (n_47), .CP (clk), .D (n_36), .Q
       (sum[12]));
  AO22D0 g2608__6783(.A1 (n_35), .A2 (n_34), .B1 (b_temp[12]), .B2
       (a_temp[12]), .Z (n_38));
  XOR2D1 g2609__3680(.A1 (n_35), .A2 (n_34), .Z (n_36));
  DFCNQD1 \sum_reg[11] (.CDN (n_47), .CP (clk), .D (n_33), .Q
       (sum[11]));
  AO22D0 g2611__1617(.A1 (n_32), .A2 (n_31), .B1 (b_temp[11]), .B2
       (a_temp[11]), .Z (n_35));
  XOR2D1 g2612__2802(.A1 (n_32), .A2 (n_31), .Z (n_33));
  DFCNQD1 \sum_reg[10] (.CDN (n_47), .CP (clk), .D (n_30), .Q
       (sum[10]));
  AO22D0 g2614__1705(.A1 (n_29), .A2 (n_28), .B1 (b_temp[10]), .B2
       (a_temp[10]), .Z (n_32));
  XOR2D1 g2615__5122(.A1 (n_29), .A2 (n_28), .Z (n_30));
  DFCNQD1 \sum_reg[9] (.CDN (n_47), .CP (clk), .D (n_27), .Q (sum[9]));
  AO22D0 g2617__8246(.A1 (n_26), .A2 (n_25), .B1 (b_temp[9]), .B2
       (a_temp[9]), .Z (n_29));
  XOR2D1 g2618__7098(.A1 (n_26), .A2 (n_25), .Z (n_27));
  DFCNQD1 \sum_reg[8] (.CDN (n_47), .CP (clk), .D (n_24), .Q (sum[8]));
  AO22D0 g2620__6131(.A1 (n_23), .A2 (n_22), .B1 (b_temp[8]), .B2
       (a_temp[8]), .Z (n_26));
  XOR2D1 g2621__1881(.A1 (n_23), .A2 (n_22), .Z (n_24));
  DFCNQD1 \sum_reg[7] (.CDN (n_47), .CP (clk), .D (n_21), .Q (sum[7]));
  AO22D0 g2623__5115(.A1 (n_20), .A2 (n_19), .B1 (b_temp[7]), .B2
       (a_temp[7]), .Z (n_23));
  XOR2D1 g2624__7482(.A1 (n_20), .A2 (n_19), .Z (n_21));
  DFCNQD1 \sum_reg[6] (.CDN (n_47), .CP (clk), .D (n_18), .Q (sum[6]));
  AO22D0 g2626__4733(.A1 (n_17), .A2 (n_16), .B1 (b_temp[6]), .B2
       (a_temp[6]), .Z (n_20));
  XOR2D1 g2627__6161(.A1 (n_17), .A2 (n_16), .Z (n_18));
  DFCNQD1 \sum_reg[5] (.CDN (n_47), .CP (clk), .D (n_15), .Q (sum[5]));
  AO22D0 g2629__9315(.A1 (n_14), .A2 (n_13), .B1 (b_temp[5]), .B2
       (a_temp[5]), .Z (n_17));
  XOR2D1 g2630__9945(.A1 (n_14), .A2 (n_13), .Z (n_15));
  DFCNQD1 \sum_reg[4] (.CDN (n_47), .CP (clk), .D (n_12), .Q (sum[4]));
  AO22D0 g2632__2883(.A1 (n_11), .A2 (n_10), .B1 (b_temp[4]), .B2
       (a_temp[4]), .Z (n_14));
  XOR2D1 g2633__2346(.A1 (n_11), .A2 (n_10), .Z (n_12));
  DFCNQD1 \sum_reg[3] (.CDN (n_47), .CP (clk), .D (n_9), .Q (sum[3]));
  AO22D0 g2635__1666(.A1 (n_8), .A2 (n_7), .B1 (b_temp[3]), .B2
       (a_temp[3]), .Z (n_11));
  XOR2D1 g2636__7410(.A1 (n_8), .A2 (n_7), .Z (n_9));
  DFCNQD1 \sum_reg[2] (.CDN (n_47), .CP (clk), .D (n_6), .Q (sum[2]));
  AO22D0 g2638__6417(.A1 (n_83), .A2 (n_4), .B1 (b_temp[2]), .B2
       (a_temp[2]), .Z (n_8));
  XOR2D1 g2639__5477(.A1 (n_83), .A2 (n_4), .Z (n_6));
  DFCNQD1 \sum_reg[1] (.CDN (n_47), .CP (clk), .D (n_84), .Q (sum[1]));
  DFCNQD1 \sum_reg[0] (.CDN (n_47), .CP (clk), .D (n_0), .Q (sum[0]));
  XOR3D1 g2644__6260(.A1 (cin_temp), .A2 (b_temp[0]), .A3 (a_temp[0]),
       .Z (n_0));
  CKXOR2D1 g2653__4319(.A1 (b_temp[2]), .A2 (a_temp[2]), .Z (n_4));
  CKXOR2D1 g2656__8428(.A1 (b_temp[12]), .A2 (a_temp[12]), .Z (n_34));
  CKXOR2D1 g2657__5526(.A1 (b_temp[13]), .A2 (a_temp[13]), .Z (n_37));
  CKXOR2D1 g2658__6783(.A1 (b_temp[10]), .A2 (a_temp[10]), .Z (n_28));
  CKXOR2D1 g2659__3680(.A1 (b_temp[9]), .A2 (a_temp[9]), .Z (n_25));
  CKXOR2D1 g2645__1617(.A1 (b_temp[3]), .A2 (a_temp[3]), .Z (n_7));
  CKXOR2D1 g2655__2802(.A1 (b_temp[15]), .A2 (a_temp[15]), .Z (n_43));
  CKXOR2D1 g2650__1705(.A1 (b_temp[4]), .A2 (a_temp[4]), .Z (n_10));
  CKXOR2D1 g2647__5122(.A1 (b_temp[7]), .A2 (a_temp[7]), .Z (n_19));
  CKXOR2D1 g2648__8246(.A1 (b_temp[6]), .A2 (a_temp[6]), .Z (n_16));
  CKXOR2D1 g2649__7098(.A1 (b_temp[5]), .A2 (a_temp[5]), .Z (n_13));
  CKXOR2D1 g2646__6131(.A1 (b_temp[8]), .A2 (a_temp[8]), .Z (n_22));
  CKXOR2D1 g2651__1881(.A1 (b_temp[14]), .A2 (a_temp[14]), .Z (n_40));
  CKXOR2D1 g2652__5115(.A1 (b_temp[11]), .A2 (a_temp[11]), .Z (n_31));
  AN2XD1 g2660__4733(.A1 (b_temp[0]), .A2 (a_temp[0]), .Z (n_1));
  DFCNQD1 cin_temp_reg(.CDN (n_47), .CP (clk), .D (cin), .Q (cin_temp));
  DFCNQD1 \a_temp_reg[2] (.CDN (n_47), .CP (clk), .D (a[2]), .Q
       (a_temp[2]));
  DFCNQD1 \b_temp_reg[1] (.CDN (n_47), .CP (clk), .D (b[1]), .Q
       (b_temp[1]));
  DFCNQD1 \a_temp_reg[10] (.CDN (n_47), .CP (clk), .D (a[10]), .Q
       (a_temp[10]));
  DFCNQD1 \b_temp_reg[8] (.CDN (n_47), .CP (clk), .D (b[8]), .Q
       (b_temp[8]));
  DFCNQD1 \a_temp_reg[13] (.CDN (n_47), .CP (clk), .D (a[13]), .Q
       (a_temp[13]));
  DFCNQD1 \b_temp_reg[14] (.CDN (n_47), .CP (clk), .D (b[14]), .Q
       (b_temp[14]));
  DFCNQD1 \a_temp_reg[7] (.CDN (n_47), .CP (clk), .D (a[7]), .Q
       (a_temp[7]));
  DFCNQD1 \b_temp_reg[2] (.CDN (n_47), .CP (clk), .D (b[2]), .Q
       (b_temp[2]));
  DFCNQD1 \a_temp_reg[12] (.CDN (n_47), .CP (clk), .D (a[12]), .Q
       (a_temp[12]));
  DFCNQD1 \b_temp_reg[6] (.CDN (n_47), .CP (clk), .D (b[6]), .Q
       (b_temp[6]));
  DFCNQD1 \a_temp_reg[15] (.CDN (n_47), .CP (clk), .D (a[15]), .Q
       (a_temp[15]));
  DFCNQD1 \b_temp_reg[10] (.CDN (n_47), .CP (clk), .D (b[10]), .Q
       (b_temp[10]));
  DFCNQD1 \b_temp_reg[7] (.CDN (n_47), .CP (clk), .D (b[7]), .Q
       (b_temp[7]));
  DFCNQD1 \b_temp_reg[3] (.CDN (n_47), .CP (clk), .D (b[3]), .Q
       (b_temp[3]));
  DFCNQD1 \a_temp_reg[8] (.CDN (n_47), .CP (clk), .D (a[8]), .Q
       (a_temp[8]));
  DFCNQD1 \b_temp_reg[4] (.CDN (n_47), .CP (clk), .D (b[4]), .Q
       (b_temp[4]));
  DFCNQD1 \b_temp_reg[9] (.CDN (n_47), .CP (clk), .D (b[9]), .Q
       (b_temp[9]));
  DFCNQD1 \b_temp_reg[11] (.CDN (n_47), .CP (clk), .D (b[11]), .Q
       (b_temp[11]));
  DFCNQD1 \b_temp_reg[5] (.CDN (n_47), .CP (clk), .D (b[5]), .Q
       (b_temp[5]));
  DFCNQD1 \b_temp_reg[12] (.CDN (n_47), .CP (clk), .D (b[12]), .Q
       (b_temp[12]));
  DFCNQD1 \b_temp_reg[15] (.CDN (n_47), .CP (clk), .D (b[15]), .Q
       (b_temp[15]));
  DFCNQD1 \a_temp_reg[3] (.CDN (n_47), .CP (clk), .D (a[3]), .Q
       (a_temp[3]));
  DFCNQD1 \a_temp_reg[1] (.CDN (n_47), .CP (clk), .D (a[1]), .Q
       (a_temp[1]));
  DFCNQD1 \a_temp_reg[4] (.CDN (n_47), .CP (clk), .D (a[4]), .Q
       (a_temp[4]));
  DFCNQD1 \a_temp_reg[6] (.CDN (n_47), .CP (clk), .D (a[6]), .Q
       (a_temp[6]));
  DFCNQD1 \a_temp_reg[9] (.CDN (n_47), .CP (clk), .D (a[9]), .Q
       (a_temp[9]));
  DFCNQD1 \a_temp_reg[0] (.CDN (n_47), .CP (clk), .D (a[0]), .Q
       (a_temp[0]));
  DFCNQD1 \a_temp_reg[14] (.CDN (n_47), .CP (clk), .D (a[14]), .Q
       (a_temp[14]));
  DFCNQD1 \a_temp_reg[5] (.CDN (n_47), .CP (clk), .D (a[5]), .Q
       (a_temp[5]));
  DFCNQD1 \b_temp_reg[0] (.CDN (n_47), .CP (clk), .D (b[0]), .Q
       (b_temp[0]));
  DFCNQD1 \a_temp_reg[11] (.CDN (n_47), .CP (clk), .D (a[11]), .Q
       (a_temp[11]));
  DFCNQD1 \b_temp_reg[13] (.CDN (n_47), .CP (clk), .D (b[13]), .Q
       (b_temp[13]));
  CKND0 g2694(.I (rst), .ZN (n_47));
  FA1D0 g2745(.A (b_temp[1]), .B (a_temp[1]), .CI (n_1), .CO (n_83), .S
       (n_84));
endmodule

